name: Push image to Docker Hub

on:
  push: # When pushing to any branch then run this action

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: ${{ secrets.REPO_NAME }}

jobs:
  push-image-to-docker-hub: # job name
    runs-on: ubuntu-latest # runner name (ubuntu latest version)

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2 # first action: checkout source code

      - name: Docker login
        run: |
          # Log into Docker Hub account
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Get current date
        id: date
        run: |
          # Get the date of the build
          echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Build the Docker image
        run: |
          # Build the Docker image and tag it with the date
          docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}

      - name: Docker Push
        run: |
          # Push the image to Docker Hub
          docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}

